### ISSUE TITLE
Wireless card not detected

### ISSUE THREAD

**Issue by ghost** [chunkingz/linsetmv1-2#1]
For some reason its telling me that linset is not detecting my wireless card. My wireless card supports packet injection. I attached my wifi adapter that also supports packet injection and it still says that there are no wifi cards found. I tired running the script while in monitor mode and in managed mode. yes i read the help.txt but it only says what i already know. Ive been waiting for this script to be translated for awhile and its a really helpful tool to have instead of running everything separately.
![sxui4f7l png](https://cloud.githubusercontent.com/assets/6226859/18888105/f170a9b8-84c4-11e6-83fe-da81d4ccd49b.jpeg)

**Comment by chunkingz** [comment]
uhm, am sorry but dats not my version, my version is completely in english and works flawlessly.

**Comment by SiNaPsEr0x** [comment]
idem form me, problem with last airmon

**Comment by ghost** [comment]
here is where things get weird. i download the zip and extract like usual to my folder. Everything in the linset folder is original and you can see that the script is your version and in english: 
![rnrerin](https://cloud.githubusercontent.com/assets/6226859/18926796/3e547026-8587-11e6-94e9-26ca71dd0a71.png). i tried running the script without root and it insists i run with root. When i do run it, everything seems to work in the beginning as i have all the dependencies into order to run linset. At the end it says that it reboots the script followed by an error on line 563.
![wdje8ic](https://cloud.githubusercontent.com/assets/6226859/18926942/aff9e9a4-8587-11e6-8906-435d9660d54f.png). If i attempt to run the script from exactly the same path again, it shows that the script has been modified back to it original state, i had pluma open to verify it.
![qcbsszw](https://cloud.githubusercontent.com/assets/6226859/18926988/dceb9700-8587-11e6-8d4e-bef77d664bb9.png). I deleted everything that had to do with linset and tried it again but i still get the same thing. Can i do something to stop the script from being re-modified. ive never really encountered this error before so am not sure how to proceed?

**Comment by chunkingz** [comment]
The issue resides in the auto update function within the script, take a look at d second screen shot, underneath u can see **"updated successfully, rebooting the script to update changes"**, it updates from the original authors site. 
For now u can check your root directory you'll see a **linset-rev33.backup** file,  copy it into ur main linset directory delete the **linsetmv-1-2.sh** file and rename d copied file. Disable ur internet connection. And rerun the script. It should work without issues. 

I'll edit the script and commit later.

**Comment by chunkingz** [comment]
On the other hand u could go ahead and edit the script after completing the above steps. 

Open the linsetmv1-2.sh with any editor of ur choice. 
Scroll down a bit or search for a function named 
**"function checkupdatess"**

If ure a n00b to coding, take note Dat functions are called. So asides d main function, it's being called later in the script. 

So u have to search for Dat name again and put a hash tag in front. Like this **"#checkupdatess"**. So Dat it's not used anymore. 

I hope this helps.

**Comment by chunkingz** [comment]
@blkv0lk @SiNaPsEr0x This issue has been resolved, so therefore am closing.
