### ISSUE TITLE
i am getting this error in both linset and fluxion

### ISSUE THREAD

**Issue by iwolv** [chunkingz/linsetmv1-2#3]
wc: /tmp/TMPflux/dump-01.csv: No such file or directory ./fluxion: line 1218: [: -le: unary operator expected cat: /tmp/TMPflux/dump-01.csv: No such file or directory expr: syntax error                         WIFI LIST    ID      MAC                      CHAN    SECU     PWR   ESSID  grep: invalid: No such file or directory grep: number: No such file or directory grep: of: No such file or directory grep: lines:: No such file or directory grep: ‘/tmp/TMPflux/dump-01.csv’: No such file or directory   1)	head: invalid number of lines: ‘/tmp/TMPflux/dump-01.csv’	 	   100%

**Comment by ghost** [comment]
Same problem here...
I am using bcm43143 (14e4:4365) with wl drivers.I have enabled monitor mode on it but still fluxion is unable to scan for wifi networks.Although airodump-ng works fine but reaver also freezes on-
" Waiting for beacon from XX:XX:XX:XX:XX:XX"
Any help is appreciated, Thanks in advance.
